version: '3.8'
services:
  # Loki for logs
  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml

  # Tempo for traces
  tempo:
    image: grafana/tempo:latest
    ports:
      - '3200:3200' # Tempo UI
    expose:
      - '4318'
      - '4317'

    command: -config.file=/etc/tempo/tempo-local.yaml
    volumes:
      - ./tempo-config.yaml:/etc/tempo/tempo-local.yaml

  # Mimir for metrics
  mimir:
    image: grafana/mimir:latest
    ports:
      - '9009:9009' # Remote-write endpoint
    command: -config.file=/etc/mimir/mimir.yaml
    volumes:
      - ./mimir-config.yaml:/etc/mimir/mimir.yaml

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
    volumes:
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  # Grafana Alloy (OTel distributor)
  alloy:
    image: grafana/alloy:latest
    ports:
      - '12345:12345'
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
    command: >
      run --server.http.listen-addr=0.0.0.0:12345 
      --storage.path=/var/lib/alloy/data 
      /etc/alloy/config.alloy
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
  docker-monitor:
    image: portainer/portainer:latest
    restart: always
    ports:
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volume/portainer-data:/data
