version: '3.8'
services:
  grafana-alloy:
    image: grafana/alloy:latest
    volumes:
      - ./agent/config.alloy:/etc/alloy/config.alloy
    ports:
      - '12345:12345'
    command: >
      run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3000:3000'
    depends_on:
      - grafana-alloy
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    command: >
      --config=/etc/grafana/grafana.ini
