multitenancy_enabled: false

server:
  http_listen_port: 9009

blocks_storage:
  backend: s3
  s3:
    endpoint: observability-minio-1:9000
    bucket_name: mimir-blocks
    access_key_id: mimir
    secret_access_key: supersecret
    insecure: true
  tsdb:
    dir: /tmp/mimir/tsdb

ruler:
  enable_api: true
ruler_storage:
  backend: s3
  s3:
    endpoint: observability-minio-1:9000
    bucket_name: mimir-ruler
    access_key_id: mimir
    secret_access_key: supersecret
    insecure: true