version: '3.9'

networks:
  kong-net:
    driver: bridge

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      # POSTGRES_DB: kong_db
      POSTGRES_MULTIPLE_DATABASES: kong_db, konga_db
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'user']
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ${PWD}/volume/postgres/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - kong-net

  kong-migration:
    image: kong:1.3.0-alpine
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong_db
      KONG_PG_USER: user
      KONG_PG_PASSWORD: 12345
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    networks:
      - kong-net
    depends_on:
      kong-database:
        condition: service_healthy

  kong:
    image: kong:1.3.0-alpine
    container_name: kong
    environment:
      KONG_LOG_LEVEL: debug
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong_db
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PG_USER: user
      KONG_PG_PASSWORD: 12345
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'
    networks:
      - kong-net
    depends_on:
      kong-database:
        condition: service_healthy

  konga-prepare:
    image: pantsel/konga:next
    container_name: konga-prepare
    command: -c prepare -a postgres -u postgresql://user:12345@kong-database:5432/konga_db
    networks:
      - kong-net
    depends_on:
      kong-database:
        condition: service_healthy

  konga:
    image: pantsel/konga:next
    container_name: konga
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: user
      DB_PASSWORD: 12345
      DB_DATABASE: konga_db
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      KONGA_HOOK_TIMEOUT: 120000
      NODE_ENV: production
    ports:
      - '1337:1337'
    networks:
      - kong-net
    depends_on:
      konga-prepare:
        condition: service_started
      kong-database:
        condition: service_healthy
