{
 "title": "soldevlife",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Http Server Request size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "testapp_http_server_request_size_bytes_bucket{}"
    }
   ]
  },
  {
   "title": "DB Connection Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "testapp_go_sql_connections_in_use{}"
    }
   ]
  },
  {
   "title": "http server active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "testapp_http_server_active_requests{}"
    }
   ]
  },
  { "title": "Infra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{state=\"used\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "testapp_process_cpu_time_seconds_total{state=~\"system|user\"}"
    }
   ]
  }
 ]
}